name = "mcp-knowledge-base"
main = "cloudflare-worker.js"
compatibility_date = "2024-03-18"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "mcp-knowledge-base-prod"

# Environment variables
[vars]
# Add your environment variables here (non-sensitive ones)
NODE_ENV = "production"

# For sensitive variables like API keys, use:
# wrangler secret put OPENAI_API_KEY
# wrangler secret put DATABASE_URL

# KV Namespaces
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "f1d9fe0c943b456c915aa75890055ebb"
preview_id = "242211ea4701408f8fe6c9f4fc141483"